### ISSUE TITLE
Make pong?

### ISSUE THREAD

**Issue by david-i** [TheSaturdayThing/Arcade#1]
I did a pull of this repo on to my RPi-4 and would like to try and compile with the default SDL2/image/mixer/ttf packages that are part of the "bookworm" OS release.

Is there a Make file for either "Pong" or "PacMan" 
or instructions that could be added to the Wiki on how to compile?
For example, I recall we were trying to use 'Cmake' to build the executable from C++ sources.

**Comment by david-i** [comment]
I have updated the [Wiki](https://github.com/TheSaturdayThing/Arcade/wiki/Installing-Operating-System-on-Raspberry-Pi-4) to show what SDL2 libs come as default on a fresh install of "bookworm"; 

Also on my Pi in /home/pi/Documents I have copied over  this repo using the command
**`$ git clone https://github.com/TheSaturdayThing/Arcade.git`**

`$ cd Arcade`  
`$ git status`    
`On branch main`    
`Your branch is up to date with 'origin/main'.`  
`$ ls -als`  
total 28  
4 drwxr-xr-x 6 pi pi 4096 Jan 29 16:54 .  
4 drwxr-xr-x 3 pi pi 4096 Jan 29 16:54 ..  
4 drwxr-xr-x 2 pi pi 4096 Jan 29 16:54 bin  
4 drwxr-xr-x 8 pi pi 4096 Jan 30 04:05 .git  
4 -rw-r--r-- 1 pi pi   64 Jan 29 16:54 README.md  
4 drwxr-xr-x 2 pi pi 4096 Jan 29 16:54 sketches  
4 drwxr-xr-x 4 pi pi 4096 Jan 29 16:54 src

**Comment by LucaFeggi** [comment]
I added the CMakeLists.txt file in Pong and Pac folders. With that and cmake installed on the raspberry pi, we should be able to compile the code.
The commands to run are here: https://rvarago.medium.com/introduction-to-cmake-for-cpp-4c464272a239
(this website is already in wiki/AdditionalLibraries)
Basically we want to generate a Makefile. To do that, we create a build folder inside PacMan or Pong, run cd to go into that directory and call the function "cmake .."
Now we should have the Makefile, so we can proceed to create the executable file in the build directory by running the command "make".

**Comment by david-i** [comment]
The default SDL2 on the bookworm release does not include the libs needed to compile the games.
I uninstalled all the SDL2 components and then downloaded/compiled/nstalled the same versions into /usr/local/lib.

$ wget https://www.libsdl.org/release/SDL2-2.26.5.tar.gz
$ wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.6.3.tar.gz
$ wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.20.1.tar.gz
$ wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.6.2.tar.gz

I was able to compile both Pong and PacMan.
Pong takes a segfault since there is no joystick, so I have to check if PacMan works.

**Comment by LucaFeggi** [comment]
Are you sure the segfault is due to the joystick not connected? 
On my windows setup, whenever the joystick is not detected, the program just prints on the console the error message (something like "no joystick connected"), and runs normally the program, with the renderer and all the game objects in it. The only thing you should notice is that you can't control the paddles, but you should see the game on the screen.
I remember the segfault happened to me as well while I was trying to compile the code. I thought it was due to the missing X11, but if you have it installed and active on your device, I don't really know.
Another problem was, only in the PacMan program, that when I was trying to load the textures from file the raspberry pi was not able to open the images cause there was not the full path of the images in the code
(
example:
texture.LoadFromFile("Textures/Pac24.png") -> was giving an error
texture.LoadFromFile("RaspPiName/user/desktop/PacMan/Textures/Pac24.png") -> or something like that, the fact is that you have to write the full directory to open the texture image
)

**Comment by david-i** [comment]
For Pong, I got the segfault at terminal when running the executable out of the 'build' directory; 
If I go up a level and make a symbolic link to 'build/Pong' and run it, the program works correcty.
This method also work for running PacMan in order to resolve the path to Textures.
